config/routes.rb
InfoDebate::Application.routes.draw do

  change_status_put = lambda do
    put 'change_status/:status_action', :action => 'change_status', :as => 'change_status'
  end

  show_modal_get = lambda do
    get 'show_modal', :action => 'show_modal', :as => 'show_modal'
  end

  namespace :admin do
    resources :users, :forums, :forum_threads do
      member do
        change_status_put.call
        show_modal_get.call
      end
    end
    
    resources :comments do
      member do
        change_status_put.call
        show_modal_get.call
        get 'answers(/:div_class)', :action => 'answers', :as => 'answers'
        get 'complaints(/:div_class)', :controller => 'complaints', :action => 'complaints', :as => 'complaints'
      end
    end
    
    resources :complaints do
      member do
        change_status_put.call
        show_modal_get.call
      end
    end
  end

  root :to => 'pages#home'
  
  match '/about', :to => 'pages#about'
  
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :string(4000)
#  thread_id  :integer          not null
#  user_id    :integer          not null
#  status     :integer          not null
#  dislike    :integer          default(0)
#  like       :integer          default(0)
#  parent_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  include Status::ModelStatus
  include Search::StandardModelSearch
    
  attr_accessible :body, :dislike, :like, :user, :thread
  
  belongs_to :parent, :class_name => "Comment", :foreign_key => "parent_id"
  belongs_to :thread, :class_name => "ForumThread"
  belongs_to :user
  
  has_many :children, :class_name => 'Comment', :foreign_key => 'parent_id',
           :order => 'created_at ASC', :dependent => :delete_all
  has_many :complaints, :autosave => true
  
  validates :body, :presence => true, :length => { :maximum => 4000 }
  validates :status, :presence => true
  validates :user_id, :presence => true
  validates :thread_id, :presence => true
  validate :verify_thread_child
  
  def verify_thread_child
    if child? && !parent.nil? && self.thread != parent.thread
      errors.add(:thread_id, I18n.t(:invalid_comment_thread, :scope => [:errors, :messages]) ||
                "Thread should be the same parent comment's thread")
    end
  end
  
  default_scope where("#{table_name}.status != #{find_status_value(:deleted)}")
  default_scope order("#{table_name}.created_at DESC")
  
  after_initialize do
    self.thread = parent.thread if child? && !parent.nil?
  end
  
  # Define configurations for status machine
  def_valid_status :approved, :rejected, :pending, :spam, :deleted
  def_un_target_status :pending
  def_terminal_status :deleted
  def_initial_status_proc :init_status
  
  # Callback that allows to create subset for target_status depending on object state
  def_contraints_to_target_status :target_status_constraint
  
  # Define callbacks for status change actions
  def_before_status_change :deleted, :exec_status_change
  
  # Define search configurations
  def_default_status_for_search :approved
  def_default_search_fields :id => :integer, :parent_id => :integer, :body => :string
  
  def_extended_search do |options|
    list = []
    list << {:query => "#{table_name}.thread_id = :thread_id",
             :params => {:thread_id => options[:thread_id]}} unless options[:thread_id].blank?
    list << {:query => "#{table_name}.user_id = :user_id",
              :params => {:user_id => options[:user_id]}} unless options[:user_id].blank?
    list << {:query => "#{table_name}.parent_id = :parent_id",
              :params => {:parent_id => options[:parent_id]}} unless options[:parent_id].blank?
    list
  end
  
  def init_status
    raise CreationModelError, I18n.t(:not_active_user, :scope => :model_creation) if (!user.nil? && !user.active?)
    raise CreationModelError, I18n.t(:not_active_thread, :scope => :model_creation) if (!thread.nil? && !thread.active?)
    :approved
  end
  
  def child?; !parent_id.nil? end
  
  private
    def exec_status_change(old_status, new_status, action)
      complaints.update_all(:status => find_status_value(new_status))
    end
    
    def target_status_constraint(status)
      if ( (!user.nil? && !user.active?) || (!thread.nil? && !thread.active?) )
        [:approved, :rejected].each {|s| status.delete(s) }
      end
      status
    end
end

app/controllers/admin/comments_controller.rb
# encoding: UTF-8

class Admin::CommentsController < Admin::AdminController

  MASS_ATTR_EXCEPTIONS = [:thread_id, :user_id, :parent_id]
  
  before_filter :init_obj_for_change_status, :only => [:change_status]
  
  # GET /admin/comments
  # GET /admin/comments.js
  def index
    @comments = Comment.search({ :term => params[:q], 
                                 :thread_id => params[:thread_id],
                                 :user_id => params[:user_id],
                                 :status => params[:status]},
                               params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def answers
    @answers = Comment.search({:parent_id => params[:id], :status => :all},
                              params[:page], LIGHTBOX_PER_PAGE)
    respond_to do |format|
      format.js
    end
  end

  # GET /admin/comments/1
  # GET /admin/comments/1.js
  def show
    @comment = Comment.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /admin/comments/1/show_modal
  # GET /admin/comments/1/show_modal.js
  def show_modal
    @comment = Comment.find(params[:id])
    respond_to do |format|
      format.html { head :not_found }
      format.js
    end
  end

  # GET /admin/comments/new
  def new
    @comment = Comment.new
  end

  # GET /admin/comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /admin/comments
  def create
    @comment = Comment.new(params[:comment].except(*MASS_ATTR_EXCEPTIONS))
    @comment.thread = get_thread params[:comment][:thread_id]
    @comment.user = get_user params[:comment][:user_id] 
    @comment.parent = get_comment params[:comment][:parent_id] 
    if @comment.save
      redirect_to [:admin, @comment], notice: t(:creation_success, scope: :action_messages, model: 'Comentário')
    else
      render action: "new"
    end
  end

  # PUT /admin/comments/1
  def update
    @comment = Comment.find(params[:id])
    @comment.thread = get_thread params[:comment][:thread_id]
    @comment.user = get_user params[:comment][:user_id] 
    @comment.parent = get_comment params[:comment][:parent_id] 
    if @comment.update_attributes(params[:comment].except(*MASS_ATTR_EXCEPTIONS))
      redirect_to [:admin, @comment], notice: t(:update_success, scope: :action_messages, model: 'Comentário')
    else
      render action: "edit"
    end
  end

  # DELETE /admin/comments/1
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to admin_comments_url, notice: t(:deletion_success, scope: :action_messages, model: 'Comentário')
  end
  
  private
    
    def init_obj_for_change_status
      @obj = Comment.find_by_id(params[:id])
    end
end

app/helpers/admin/comment_helper.rb
module Admin::CommentHelper
  
  def item_list_class(id)
    "answerlist_#{id}"
  end
  
end

app/views/admin/comments/_answer.html.erb
<li class="item" id="answer_<%= answer.id %>">
  <div class="item-body">
    <span class="item-heading time">
      <b><%= time_ago_in_words(answer.created_at) %></b>
    </span>
    <div class="item-title">
      <h4 class="item-heading">
        <%= link_to truncate_text(answer.thread.name), admin_forum_thread_path(answer.thread) %>
      </h4>
    </div>
    <spam class="item-heading">
      <b>Usuário:</b> <%= link_to answer.user.name, admin_user_path(answer.user) %>
    </spam>
    <span class="item-heading username">
      <b><%= answer.user.username %></b>
    </span>
    <div class="item-text">
      <%= simple_format answer.body %>
    </div>
  </div>
  <div class="item-body-footer">
    <spam class="item-footer item-footer-id">
      <strong>ID: <%= answer.id %></strong>
    </spam>
    <spam class="item-footer item-footer-id">
      <strong>Status: <%= t answer.status, :scope => :status %></strong>
    </spam>
    <%= link_to "Visualizar", admin_comment_path(answer), :class => "item-footer-btn btn-view" %>
    <% unless answer.children.empty? %>
      <%= link_to "Ver Respostas", answers_admin_comment_path(answer, item_list_class(answer.id)),
                  :class => "item-footer-btn btn-view", :remote => true,
                  :onclick => "javascript:$(this).remove();" %>
    <% end %>
  </div>
  <div>
    <ul class="item-answer <%= item_list_class(answer.id) %>"></ul>
  </div>
</li>

app/views/admin/comments/_answers.html.erb
<%= render :partial => 'answer', :collection => @answers %>
<% if @answers.total_pages > @answers.current_page %>
  <li>
    <b><%= link_to "Ver Mais", answers_admin_comment_path(params[:id], item_list_class(params[:id]), 
                                                          :page => @answers.current_page + 1),
                               :class => "btn-read-more", :remote => true,
                               :onclick => "javascript:$(this).parent().parent().remove();" %></b>
  </li>
<% end %>

app/views/admin/comments/_comment.html.erb
<% entity_id = "comment_#{comment.id}" %>
<li class="item" id="<%= entity_id %>">
  <div class="item-body">
    <span class="item-heading time">
      <b><%= time_ago_in_words(comment.created_at) %></b>
    </span>
    <div class="item-title">
      <h4 class="item-heading">
        <%= link_to comment.thread.name, show_modal_admin_forum_thread_path(comment.thread),
                    :remote => true, data: { toggle: "modal", target: "#admin-modal" },
                    :id => comment.thread.id %>
      </h4>
    </div>
    <spam class="item-heading">
      <b>Usuário:</b> <%= link_to comment.user.name, show_modal_admin_user_path(comment.user),
                   :remote => true, data: { toggle: "modal", target: "#admin-modal" } %>
    </spam>
    <span class="item-heading username">
      <b><%= comment.user.username %></b>
    </span>
    <div class="item-text">
      <%= simple_format comment.body %>
    </div>
  </div>
  <div class="item-body-footer">
    <spam class="item-footer item-footer-id">
      <strong>ID: <%= comment.id %></strong>
    </spam>
    <%= link_to "Visualizar", admin_comment_path(comment), :class => "item-footer-btn btn-view" %>
    <%= link_to "Pré-visualizar", show_modal_admin_comment_path(comment), :remote => true, 
         :class => "item-footer-btn btn-preview", data: { toggle: "modal", target: "#admin-modal" } %>
    <% unless comment.parent.nil? %>
      <%= link_to "Resposta a", show_modal_admin_comment_path(comment.parent),
           :remote => true, :class => "item-footer-btn btn-parent",
           data: { toggle: "modal", target: "#admin-modal" } %>
    <% end %>
    <% unless comment.children.empty? %>
      <%= link_to "Respostas", answers_admin_comment_path(comment), :remote => true, :class => "item-footer-btn btn-answers",
           data: { toggle: "modal", target: "#admin-modal" } %>
    <% end %>
    <% unless comment.complaints.empty? %>
      <%= link_to "Reclamações", complaints_admin_comment_path(comment), :remote => true, 
           :class => "item-footer-btn btn-complaints", data: { toggle: "modal", target: "#admin-modal" } %>
    <% end %>
    <spam class="item-footer-right">
      <% generate_status_change_actions(comment, :comment).each do |action| %>
        <strong><%= link_to action[:label], action[:path], :remote => true,
                    :data => {:confirm => action[:confirmation_msg], :method => action[:method],
                              :custom_reload => true, :reload_entityid => entity_id },
                    :class => "item-footer-btn btn-#{action[:type]}" %></strong>
      <% end %>
    </spam>
  </div>
</li>

app/views/admin/comments/_fields.html.erb
<% @comment.thread = ForumThread.find_by_id(params[:thread_id]) unless params[:thread_id].nil? %>
<% thread_path = admin_forum_thread_path(@comment.thread) unless @comment.thread.nil? %>
<%= render 'shared/admin/select2_js_template',
     :field_name => "comment_thread_id",
     :label => "Thread",
     :obj => @comment.thread,
     :index_path => admin_forum_threads_path,
     :show_path => thread_path %>

<% @comment.user = User.find_by_id(params[:user_id]) unless params[:user_id].nil? %>
<% user_path = admin_user_path(@comment.user) unless @comment.user.nil? %>
<%= render 'shared/admin/select2_js_template',
     :field_name => "comment_user_id",
     :label => "Usuário",
     :obj => @comment.user,
     :index_path => admin_users_path,
     :show_path => user_path %>

<%= render 'shared/error_messages', :object => f.object %>
<% unless f.object.new_record? %>
  <%= render 'shared/field_show', :label => "Id", :value => f.object.id %>
  <%= render 'shared/field_show', :label => "Status", :value => t(f.object.status, :scope => :status_label)  %>
<% end %>

<%= render 'shared/field', :f => f, :field_name => :thread_id %>
<%= render 'shared/field', :f => f, :field_name => :user_id %>
<%= render 'shared/field', :f => f, :field_name => :parent_id %>
<%= render 'shared/field', :f => f, :field_type => :text_area, :field_name => :body %>

app/views/admin/comments/_index_list.html.erb
<%= will_paginate %>
<div>
<ul class="item-list">
  <% if @comments.length > 0 %>
    <%= render @comments %>
  <% else %>
    <li class="item-empty"><%= t :comment, :scope => :empty_list %></li>
  <% end %>
</ul>
</div>
<%= will_paginate %>

app/views/admin/comments/_show.html.erb
<% javascript 'admin/show' %>

<%= render 'shared/admin_title_options', :title => "Visualização de Comentário",
           :options => generate_status_change_actions(@comment, :comment) +
                       [ {:label => "Voltar", :path => admin_comments_path, :type => "info"} ] %>

<%= render 'shared/status_message' %>

<%= render 'show_fields' %>

<%= hidden_field_tag 'model_path', admin_comment_path(@comment) %>

app/views/admin/comments/_show_fields.html.erb
<% opened_from_modal ||= false %>

<div class="form-horizontal">
  <%= render 'shared/field_show', :label => "Id", :value => @comment.id %>
  <%= render 'shared/field_show', :label => "Status", :value => t(@comment.status, :scope => :status_label) %>
  <%= render 'shared/field_show', :label => "Thread", 
                                  :link => link_to("#{@comment.thread.name} (Id: #{@comment.thread.id})",
                                                   show_modal_admin_forum_thread_path(@comment.thread),
                                                    :remote => true, data: modal_data_map(opened_from_modal)) %>
  <%= render 'shared/field_show', :label => "Usuário",
                                  :link => link_to("#{@comment.user.name} (Id: #{@comment.user.id})", 
                                                    show_modal_admin_user_path(@comment.user),
                                                    :remote => true, data: modal_data_map(opened_from_modal)) %>
  <% unless @comment.parent.nil? %>
    <%= render 'shared/field_show', :label => "Resposta a",
                                    :link => link_to("#{@comment.parent.body.first(40)} (Id: #{@comment.parent.id})",
                                                     show_modal_admin_comment_path(@comment.parent),
                                                     :remote => true, data: modal_data_map(opened_from_modal)) %>
  <% end %>
  <%= render 'shared/field_show', :label => "Texto", :value => simple_format(@comment.body) %>
  <%= render 'shared/field_show', :label => "Criado em", :value => l(@comment.created_at) %>
  <%= render 'shared/field_show', :label => "Atualizado em", :value => l(@comment.updated_at) %>
</div>

app/views/admin/comments/answers.js.erb
<% if params[:div_class].nil? %>
  <% answers = "<ul class=\"item-list #{item_list_class(params[:id])}\">#{render :partial => 'answers'}</ul>" %>
  $(".modal-body-content").html("<%= raw escape_javascript answers %>");
  $(".modal-title").html("Pré-visualização de Comentário");
<% else %>
  $(".<%= params[:div_class] %>").append("<%= escape_javascript render :partial => 'answers' %>");
<% end %>
$(".modal-footer > .extra-buttons").empty();

app/views/admin/comments/edit.html.erb
<%= render 'shared/admin_title_options', :title => "Atualização de Comentário",
           :options => [ {:label => "Voltar", :path => admin_comments_path, :type => "info"} ] %>

<%= form_for([:admin, @comment], :html => {:class => "form-horizontal"}) do |f| %>
  <%= render 'fields', :f => f %>	
  <div class="controls"> 
    <%= f.submit "Salvar", :class => "btn btn-primary btn-large" %>
  </div>
<% end %>

app/views/admin/comments/index.html.erb
<% javascript 'admin/list' %>
<% javascript 'admin/custom_reload' %>

<%= render 'shared/admin_title_options', :title => "Lista de Comentários" %>
<%= render 'shared/status_message' %>

<% thread = ForumThread.find_by_id(params[:thread_id]) %>
<% thread_path = admin_forum_thread_path(thread) unless thread.nil? %>
<%= render 'shared/admin/select2_js_template',
     :field_name => "thread_id",
     :label => "Thread",
     :obj => thread,
     :index_path => admin_forum_threads_path,
     :show_path => thread_path %>

<% user = User.find_by_id(params[:user_id]) %>
<% user_path = admin_user_path(user) unless user.nil? %>
<%= render 'shared/admin/select2_js_template',
     :field_name => "user_id",
     :label => "Usuário",
     :obj => user,
     :index_path => admin_users_path,
     :show_path => user_path %>

<%= render 'shared/admin/search_form', :path => admin_comments_path,
      :fields => {:q => {:tag => :text_field_tag, :class => "input-medium search-query"},
                  :status => {:tag => :hidden_field_tag},
                  :thread_id => {:tag => :hidden_field_tag},
                  :user_id => {:tag => :hidden_field_tag}} %>

<%= render 'shared/admin/status_options', :status_options => Comment.valid_status,
           :status_default => Comment.default_status_for_search %>

<div class="index_list">
  <%= render 'index_list' %>
</div>

app/views/admin/comments/index.js.erb
$(".index_list").html("<%= escape_javascript render('index_list', :formats => [:html]) %>");

app/views/admin/comments/new.html.erb
<%= render 'shared/admin_title_options', :title => "Nova Comentário",
           :options => [ {:label => "Voltar", :path => admin_comments_path, :type => "info"} ] %>

<%= form_for([:admin, @comment], :html => {:class => "form-horizontal"}) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="controls"> 
    <%= f.submit "Salvar", :class => "btn btn-primary btn-large" %>
  </div>
<% end %>

app/views/admin/comments/show_modal.js.erb
$(".modal-body-content").html("<%= escape_javascript render('show_fields', :opened_from_modal => true) %>");
$(".modal-title").html("Pré-visualização de Comentário");
<%= render "shared/admin/modal_buttons", :obj => @comment, :resource_name => :comment %>