config/routes.rb
InfoDebate::Application.routes.draw do

  change_status_put = lambda do
    put 'change_status/:status_action', :action => 'change_status', :as => 'change_status'
  end

  show_modal_get = lambda do
    get 'show_modal', :action => 'show_modal', :as => 'show_modal'
  end

  namespace :admin do
    resources :users, :forums, :forum_threads do
      member do
        change_status_put.call
        show_modal_get.call
      end
    end
    
    resources :comments do
      member do
        change_status_put.call
        show_modal_get.call
        get 'answers(/:div_class)', :action => 'answers', :as => 'answers'
        get 'complaints(/:div_class)', :controller => 'complaints', :action => 'complaints', :as => 'complaints'
      end
    end
    
    resources :complaints do
      member do
        change_status_put.call
        show_modal_get.call
      end
    end
  end

  root :to => 'pages#home'
  
  match '/about', :to => 'pages#about'
  
end

app/models/forum_thread.rb
# == Schema Information
#
# Table name: forum_threads
#
#  id          :integer          not null, primary key
#  name        :string(100)      not null
#  description :string(255)
#  url         :string(500)
#  status      :integer          not null
#  content_id  :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  forum_id    :integer          not null
#

class ForumThread < ActiveRecord::Base
  include Status::ModelStatus
  include Search::StandardModelSearch
  
  attr_accessible :content_id, :description, :name, :url
  
  belongs_to :forum
  has_many :comments, :foreign_key => :thread_id, :autosave => true
  has_many :complaints, :through => :comments
  
  validates :name, :presence => true, :length => { :maximum => 255 }
  validates :description, :length => { :maximum => 255 }
  validates :status, :presence => true
  validates :url, :length => { :maximum => 500 }
  validates :forum_id, :presence => true
  
  default_scope where("#{table_name}.status != #{find_status_value(:deleted)}")
  default_scope order("#{table_name}.name")
  
  # Define configurations for status machine
  def_valid_status :active, :inactive, :deleted
  def_terminal_status :deleted
  def_initial_status_proc :init_status
  
  # Callback that allows to create subset for target_status depending on object state
  def_contraints_to_target_status :target_status_constraint
  
  # Define callbacks for status change actions
  def_before_status_change :inactive, :deleted, :exec_status_change
  
  # Define search configurations
  def_default_status_for_search :active
  def_default_search_fields :id => :integer, :name => :string, :description => :string
  
  def_extended_search do |options|
    [{:query => "forum_id = :forum_id", :params => {:forum_id => options[:forum_id]}}] unless options[:forum_id].blank?
  end
  
  private
  
    def init_status
      return :inactive if !forum.nil? && !forum.active?
      :active
    end
    
    def exec_status_change(old_status, new_status, action)
      s = new_status
      s = :rejected if new_status == :inactive
      complaints.update_all(:status => find_status_value(s)) if new_status != :inactive
      comments.update_all(:status => find_status_value(s))
    end
    
    def target_status_constraint(status)
      if !forum.nil? && !forum.active?
        [:active, :inactive].each {|s| status.delete(s) }
      end
      status
    end
end

app/controllers/admin/forum_threads_controller.rb
class Admin::ForumThreadsController < Admin::AdminController
  
  MASS_ATTR_EXCEPTIONS = [:forum_id]
  
  before_filter :init_obj_for_change_status, :only => [:change_status]
  
  # GET /admin/forum_threads
  # GET /admin/forum_threads.json
  def index
    respond_to do |format|
      format.html { 
        @forum_threads = ForumThread.search({:term => params[:q], 
                                            :status => params[:status], :forum_id => params[:forum_id]},
                                            params[:page])
      }
      format.json { render :json => parse_list_for_js_response(search_by_name(ForumThread)) }
    end
  end

  # GET /admin/forum_threads/1
  # GET /admin/forum_threads/1.json
  # GET /admin/forum_threads/1.js
  def show
    @forum_thread = ForumThread.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => parse_for_js_response(@forum_thread) }
      format.js
    end
  end
  
  # GET /admin/forum_threads/1/show_modal
  # GET /admin/forum_threads/1/show_modal.js
  def show_modal
    @forum_thread = ForumThread.find(params[:id])
    respond_to do |format|
      format.html { head :not_found }
      format.js
    end
  end

  # GET /admin/forum_threads/new
  def new
    @forum_thread = ForumThread.new
  end

  # GET /admin/forum_threads/1/edit
  def edit
    @forum_thread = ForumThread.find(params[:id])
  end

  # POST /admin/forum_threads
  def create
    @forum_thread = ForumThread.new(params[:forum_thread].except(*MASS_ATTR_EXCEPTIONS))
    @forum_thread.forum = get_forum params[:forum_thread][:forum_id]
    if @forum_thread.save
      redirect_to [:admin, @forum_thread], notice: t(:creation_success, scope: :action_messages, model: 'Thread')
    else
      render action: "new"
    end
  end

  # PUT /admin/forum_threads/1
  def update
    @forum_thread = ForumThread.find(params[:id])
    @forum_thread.forum = get_forum params[:forum_thread][:forum_id] 
    if @forum_thread.update_attributes(params[:forum_thread].except(*MASS_ATTR_EXCEPTIONS))
      redirect_to [:admin, @forum_thread], notice: t(:update_success, scope: :action_messages, model: 'Thread')
    else
      render action: "edit"
    end
  end
  
  # DELETE /admin/forum_threads/1
  def destroy
    @forum_thread = ForumThread.find(params[:id])
    @forum_thread.destroy
    redirect_to admin_forum_threads_url, notice: t(:deletion_success, scope: :action_messages, model: 'Thread')
  end

  private
    
    def init_obj_for_change_status
      @obj = ForumThread.find(params[:id])
    end
end

app/views/admin/forum_threads/_fields.html.erb
<% @forum_thread.forum = Forum.find_by_id(params[:forum_id]) unless params[:forum_id].nil? %>
<% forum_path = admin_forum_path(@forum_thread.forum) unless @forum_thread.forum.nil? %>
<%= render 'shared/admin/select2_js_template',
     :field_name => "forum_thread_forum_id",
     :label => "Forum",
     :obj => @forum_thread.forum,
     :index_path => admin_forums_path,
     :show_path => forum_path %>

<%= render 'shared/error_messages', :object => f.object %>
<% unless f.object.new_record? %>
  <%= render 'shared/field_show', :label => "Id", :value => f.object.id %>
  <%= render 'shared/field_show', :label => "Status", :value => t(f.object.status, :scope => :status_label)  %>
<% end %>
<%= render 'shared/field', :f => f, :field_name => :name %>
<%= render 'shared/field', :f => f, :field_name => :description %>
<%= render 'shared/field', :f => f, :field_name => :forum_id %>

app/views/admin/forum_threads/_forum_thread.html.erb
<tr>
  <td><%= forum_thread.id %></td>
  <td><%= forum_thread.name %></td>
  <td><%= t forum_thread.status, :scope => 'status' %></td>
  <td><%= forum_thread.forum.name %></td>
  <td><%= forum_thread.description %></td>
  <td>
    <%= render 'shared/table_action', :action => "show", :path => admin_forum_thread_path(forum_thread) %>
    <%= render 'shared/table_action', :action => "edit", :path => edit_admin_forum_thread_path(forum_thread) %>
    <%= render 'shared/table_action', :action => "delete", :path => admin_forum_thread_path(forum_thread) %>
  </td>
</tr>

app/views/admin/forum_threads/_show.html.erb
<% javascript 'admin/show' %>

<%= render 'shared/admin_title_options', :title => "Visualização de Thread",
           :options => [ {:label => "Alterar", :path => edit_admin_forum_thread_path(@forum_thread), :type => "info"} ] +
                       generate_status_change_actions(@forum_thread, :forum_thread) +
                       [ {:label => "Voltar", :path => admin_forum_threads_path, :type => "info"} ] %>

<%= render 'shared/status_message' %>

<%= render 'show_fields' %>

<%= hidden_field_tag 'model_path', admin_forum_thread_path(@forum_thread) %>

app/views/admin/forum_threads/_show_fields.html.erb
<% opened_from_modal ||= false %>

<div class="form-horizontal">
  <%= render 'shared/field_show', :label => "Id", :value => @forum_thread.id %>
  <%= render 'shared/field_show', :label => "Nome", :value => @forum_thread.name %>
  <%= render 'shared/field_show', :label => "Status", :value => t(@forum_thread.status, :scope => :status_label) %>
  <%= render 'shared/field_show', :label => "Descrição", :value => @forum_thread.description %>
  <%= render 'shared/field_show', :label => "Forum", 
                                  :link => link_to("#{@forum_thread.forum.name} (Id: #{@forum_thread.forum.id})", 
                                                   show_modal_admin_forum_path(@forum_thread.forum),
                                                    :remote => true, data: modal_data_map(opened_from_modal)) %>
  <%= render 'shared/field_show', :label => "Criado em", :value => l(@forum_thread.created_at) %>
  <%= render 'shared/field_show', :label => "Atualizado em", :value => l(@forum_thread.updated_at) %>
</div>

app/views/admin/forum_threads/change_status.js.erb
<%= render 'shared/admin/status_change/fixed_alert' %>
<%= render 'shared/admin/status_change/delete_case' %>
<%= render 'shared/admin/status_change/reload_page' %>

app/views/admin/forum_threads/edit.html.erb
<%= render 'shared/admin_title_options', :title => "Atualização de Thread",
           :options => [ {:label => "Voltar", :path => admin_forum_threads_path, :type => "info"} ] %>

<%= form_for([:admin, @forum_thread], :html => {:class => "form-horizontal"}) do |f| %>
  <%= render 'fields', :f => f %>	
  <div class="controls"> 
    <%= f.submit "Salvar", :class => "btn btn-primary btn-large" %>
  </div>
<% end %>

app/views/admin/forum_threads/index.html.erb
<%= render 'shared/admin_title_options', :title => "Lista de Threads",
           :options => [ {:label => "Nova Thread", :path => new_admin_forum_thread_path, :type => "info"} ] %>
<%= render 'shared/status_message' %>

<% forum = Forum.find_by_id(params[:forum_id]) %>
<% forum_path = admin_forum_path(forum) unless forum.nil? %>
<%= render 'shared/admin/select2_js_template',
     :field_name => "forum_id",
     :label => "Forum",
     :obj => forum,
     :index_path => admin_forums_path,
     :show_path => forum_path %>

<%= render 'shared/admin/search_form', :path => admin_forum_threads_path,
      :fields => {:q => {:tag => :text_field_tag, :class => "input-medium search-query"},
                  :status => {:tag => :hidden_field_tag},
                  :forum_id => {:tag => :hidden_field_tag} } %>

<%= render 'shared/admin/status_options', :status_options => ForumThread.valid_status,
           :status_default => ForumThread.default_status_for_search %>

<%= will_paginate %>

<table class="table table-hover">
  <tr>
    <th>Id</th>
    <th>Nome</th>
    <th>Status</th>
    <th>Forum</th>
    <th>Descrição</th>
    <th></th>
  </tr>
  <% if @forum_threads.empty? %>
    <tr><td colspan="5"><%= t :forum_thread, :scope => :empty_list %></td></tr>
  <% else %>
    <%= render @forum_threads %>
  <% end %>
</table>

<%= will_paginate %>

app/views/admin/forum_threads/new.html.erb
<%= render 'shared/admin_title_options', :title => "Nova Thread",
           :options => [ {:label => "Voltar", :path => admin_forum_threads_path, :type => "info"} ] %>

<%= form_for([:admin, @forum_thread], :html => {:class => "form-horizontal"}) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="controls"> 
    <%= f.submit "Salvar", :class => "btn btn-primary btn-large" %>
  </div>
<% end %>

app/views/admin/forum_threads/show.html.erb
<%= render 'show' %>

app/views/admin/forum_threads/show_modal.js.erb
$(".modal-body-content").html("<%= escape_javascript render('show_fields', :opened_from_modal => true) %>");
$(".modal-title").html("Pré-visualização de Thread");
<%= render "shared/admin/modal_buttons", :obj => @forum_thread, :resource_name => :forum_thread %>