config/routes.rb
InfoDebate::Application.routes.draw do

  change_status_put = lambda do
    put 'change_status/:status_action', :action => 'change_status', :as => 'change_status'
  end

  show_modal_get = lambda do
    get 'show_modal', :action => 'show_modal', :as => 'show_modal'
  end

  namespace :admin do
    resources :users, :forums, :forum_threads do
      member do
        change_status_put.call
        show_modal_get.call
      end
    end
    
    resources :comments do
      member do
        change_status_put.call
        show_modal_get.call
        get 'answers(/:div_class)', :action => 'answers', :as => 'answers'
        get 'complaints(/:div_class)', :controller => 'complaints', :action => 'complaints', :as => 'complaints'
      end
    end
    
    resources :complaints do
      member do
        change_status_put.call
        show_modal_get.call
      end
    end
  end

  root :to => 'pages#home'
  
  match '/about', :to => 'pages#about'
  
end

app/models/forum.rb
# == Schema Information
#
# Table name: forums
#
#  id          :integer          not null, primary key
#  name        :string(100)      not null
#  description :string(255)
#  status      :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Forum < ActiveRecord::Base
  include Status::ModelStatus
  include Search::StandardModelSearch
  
  attr_accessible :description, :name

  has_many :threads, :class_name => "ForumThread", :autosave => true

  validates :name, :presence => true, :length => { :maximum => 100 }
  validates :description, :length => { :maximum => 255 }
  validates :status, :presence => true
  
  default_scope where("#{table_name}.status != #{find_status_value(:deleted)}")
  default_scope order("#{table_name}.name")
  
  # Define configurations for status machine
  def_valid_status :active, :inactive, :deleted
  def_terminal_status :deleted
  def_initial_status :active
    
  # Define callbacks for status change actions
  def_before_status_change :inactive, :deleted, :exec_status_change
  
  # Define search configurations
  def_default_status_for_search :active
  def_default_search_fields :id => :integer, :name => :string, :description => :string
  
  private
    def exec_status_change(old_status, new_status, action)
      threads.each {|thread| thread.send(action) }
    end
end

app/controllers/admin/forums_controller.rb
# encoding: UTF-8

class Admin::ForumsController < Admin::AdminController

  before_filter :init_obj_for_change_status, :only => [:change_status]

  # GET /admin/forums
  # GET /admin/forums.json
  def index
    respond_to do |format|
      format.html { @forums = Forum.search({:term => params[:q], :status => params[:status]}, params[:page]) }
      format.json { render :json => parse_list_for_js_response(search_by_name(Forum)) }
    end
  end

  # GET /admin/forums/1
  # GET /admin/forums/1.json
  def show
    @forum = Forum.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => parse_for_js_response(@forum) }
    end
  end

  # GET /admin/forums/1/show_modal
  def show_modal
    @forum = Forum.find(params[:id])
    respond_to do |format|
      format.html { head :not_found }
      format.js
    end
  end

  # GET /admin/forums/new
  def new
    @forum = Forum.new
  end

  # GET /admin/forums/1/edit
  def edit
    @forum = Forum.find(params[:id])
  end

  # POST /admin/forums
  def create
    @forum = Forum.new(params[:forum])
    if @forum.save
      redirect_to [:admin, @forum], notice: t(:creation_success, scope: :action_messages, model: 'Forum')
    else
      render action: "new"
    end
  end

  # PUT /admin/forums/1
  def update
    @forum = Forum.find(params[:id])
    if @forum.update_attributes(params[:forum])
      redirect_to [:admin, @forum], notice: t(:update_success, :scope => :action_messages, :model => 'Forum')
    else
      render action: "edit"
    end
  end

  # DELETE /admin/forums/1
  def destroy
    @forum = Forum.find(params[:id])
    @forum.destroy
    redirect_to admin_forums_url, notice: t(:deletion_success, :scope => :action_messages, :model => 'Forum')
  end

  private
  
    def init_obj_for_change_status
      @obj = Forum.find(params[:id])
    end
end

app/views/admin/forums/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<% unless f.object.new_record? %>
  <%= render 'shared/field_show', :label => "Id", :value => f.object.id %>
  <%= render 'shared/field_show', :label => "Status", :value => t(f.object.status, :scope => :status_label)  %>
<% end %>
<%= render 'shared/field', :f => f, :field_name => :name %>
<%= render 'shared/field', :f => f, :field_name => :description %>

app/views/admin/forums/_forum.html.erb
<tr>
  <td><%= forum.id %></td>
  <td><%= forum.name %></td>
  <td><%= t forum.status, :scope => 'status' %></td>
  <td><%= forum.description %></td>
  <td>
    <%= render 'shared/table_action', :action => "show", :path => admin_forum_path(forum) %>
    <%= render 'shared/table_action', :action => "edit", :path => edit_admin_forum_path(forum) %>
    <%= render 'shared/table_action', :action => "delete", :path => admin_forum_path(forum) %>
  </td>
</tr>

app/views/admin/forums/_show.html.erb
<%= render 'shared/admin_title_options', :title => "Visualização de Forum",
           :options => [ {:label => "Nova Thread", :path => new_admin_forum_thread_path(:forum_id => @forum.id), 
                          :type => "info"},
                         {:label => "Alterar", :path => edit_admin_forum_path(@forum), :type => "info"}] +
                       generate_status_change_actions(@forum, :forum) +
                       [ {:label => "Voltar", :path => admin_forums_path, :type => "info"} ] %>

<%= render 'shared/status_message' %>

<%= render 'show_fields' %>

<% unless @forum.threads.empty? %>
<div>
  <h3>Threads associadas:</h3>
  <ul class="unstyled" style="margin-left: 30px;">
    <% limit = 5 %>
    <% @forum.threads.first(limit).each do |thread| %>
      <li style="margin-bottom: 10px;">
        <%= link_to "#{thread.name} (ID: #{thread.id})", admin_forum_thread_path(thread) %>
      </li>
    <% end %>
    <% if @forum.threads.length > limit %>
      <%= link_to "Ver todos", admin_forum_threads_path(:forum_id => @forum.id) %>
    <% end %>
  </ul>
</div>
<% end %>

app/views/admin/forums/_show_fields.html.erb
<div class="form-horizontal">
  <%= render 'shared/field_show', :label => "Id", :value => @forum.id %>
  <%= render 'shared/field_show', :label => "Nome", :value => @forum.name %>
  <%= render 'shared/field_show', :label => "Status", :value => t(@forum.status, :scope => :status_label) %>
  <%= render 'shared/field_show', :label => "Descrição", :value => @forum.description %>
  <%= render 'shared/field_show', :label => "Criado em", :value => l(@forum.created_at) %>
  <%= render 'shared/field_show', :label => "Atualizado em", :value => l(@forum.updated_at) %>
</div>

app/views/admin/forums/edit.html.erb
<%= render 'shared/admin_title_options', :title => "Atualização de Forum",
           :options => [ {:label => "Nova Thread", :path => new_admin_forum_thread_path(:forum_id => @forum.id),
                          :type => "info"},
                         {:label => "Voltar", :path => admin_forums_path, :type => "info"} ] %>

<%= form_for([:admin, @forum], :html => {:class => "form-horizontal"}) do |f| %>
  <%= render 'fields', :f => f %>	
  <div class="controls"> 
    <%= f.submit "Salvar", :class => "btn btn-primary btn-large" %>
  </div>
<% end %>

app/views/admin/forums/index.html.erb
<%= render 'shared/admin_title_options', :title => "Lista de Forums",
           :options => [ {:label => "Novo Forum", :path => new_admin_forum_path, :type => "info"} ] %>
<%= render 'shared/status_message' %>

<%= render 'shared/admin/search_form', :path => admin_forums_path,
      :fields => {:q => {:tag => :text_field_tag, :class => "input-medium search-query"},
                  :status => {:tag => :hidden_field_tag} } %>

<%= render 'shared/admin/status_options', :status_options => Forum.valid_status,
           :status_default => Forum.default_status_for_search %>

<%= will_paginate %>

<table class="table table-hover">
  <tr>
    <th>Id</th>
    <th>Nome</th>
    <th>Status</th>
    <th>Descrição</th>
    <th></th>
  </tr>
  <% if @forums.empty? %>
    <tr><td colspan="5"><%= t :forum, :scope => :empty_list %></td></tr>
  <% else %>
    <%= render @forums %>
  <% end %>
</table>

<%= will_paginate %>

app/views/admin/forums/new.html.erb
<%= render 'shared/admin_title_options', :title => "Novo Forum",
           :options => [ {:label => "Voltar", :path => admin_forums_path, :type => "info"} ] %>

<%= form_for([:admin, @forum], :html => {:class => "form-horizontal"}) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="controls"> 
    <%= f.submit "Salvar", :class => "btn btn-primary btn-large" %>
  </div>
<% end %>

app/views/admin/forums/show_modal.js.erb
$(".modal-body-content").html("<%= escape_javascript render('show_fields', :opened_from_modal => true) %>");
$(".modal-title").html("Pré-visualização de Forum");
<%= render "shared/admin/modal_buttons", :obj => @forum, :resource_name => :forum %>