config/routes.rb
InfoDebate::Application.routes.draw do

  change_status_put = lambda do
    put 'change_status/:status_action', :action => 'change_status', :as => 'change_status'
  end

  show_modal_get = lambda do
    get 'show_modal', :action => 'show_modal', :as => 'show_modal'
  end

  namespace :admin do
    resources :users, :forums, :forum_threads do
      member do
        change_status_put.call
        show_modal_get.call
      end
    end
    
    resources :comments do
      member do
        change_status_put.call
        show_modal_get.call
        get 'answers(/:div_class)', :action => 'answers', :as => 'answers'
        get 'complaints(/:div_class)', :controller => 'complaints', :action => 'complaints', :as => 'complaints'
      end
    end
    
    resources :complaints do
      member do
        change_status_put.call
        show_modal_get.call
      end
    end
  end

  root :to => 'pages#home'
  
  match '/about', :to => 'pages#about'
  
end

app/models/complaint.rb
# == Schema Information
#
# Table name: complaints
#
#  id         :integer          not null, primary key
#  comment_id :integer
#  body       :string(4000)
#  status     :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Complaint < ActiveRecord::Base
  include Status::ModelStatus
  include Search::StandardModelSearch
    
  attr_accessible :body
  
  belongs_to :comment
  belongs_to :user
  
  has_one :thread, :class_name => "ForumThread", :through => :comment
  
  validates :body, :presence => true, :length => { :maximum => 4000 }
  validates :status, :presence => true
  validates :comment_id, :presence => true
  validates :user_id, :presence => true
  
  default_scope where("#{table_name}.status != #{find_status_value(:deleted)}")
  default_scope order("#{table_name}.created_at DESC")
  
  # Define configurations for status machine
  def_valid_status :approved, :rejected, :pending, :deleted
  def_un_target_status :pending
  def_terminal_status :deleted
  def_initial_status_proc :init_status
  
  # Define callbacks for status change actions
  def_before_status_change :approved, :reject_comment
  
  # Define search configurations
  def_default_status_for_search :pending
  def_default_search_fields :id => :integer, :comment_id => :integer, :body => :string
  def_joins_for_search :comment, :thread
  
  def_extended_search do |options|
    list = []
    list << {:query => "#{table_name}.user_id = :user_id",
              :params => {:user_id => options[:user_id]}} unless options[:user_id].blank?
    list << {:query => "comments.thread_id = :thread_id",
             :params => {:thread_id => options[:thread_id]}} unless options[:thread_id].blank?
    list << {:query => "forum_threads.forum_id = :forum_id",
             :params => {:forum_id => options[:forum_id]}} unless options[:forum_id].blank?
    list << {:query => "#{table_name}.comment_id = :comment_id",
             :params => {:comment_id => options[:comment_id]}} unless options[:comment_id].blank?
    list
  end
  
  private
  
    def init_status
      raise CreationModelError, I18n.t(:not_active_user, :scope => :model_creation) if (!user.nil? && !user.active?)
      return :rejected if (!comment.nil? && !comment.approved?)
      :pending
    end
    
    def reject_comment(old_status, new_status, action)
      comment.reject! if !comment.nil? && comment.approved?
    end
end

app/controllers/admin/complaints_controller.rb
# encoding: UTF-8

class Admin::ComplaintsController < Admin::AdminController

  MASS_ATTR_EXCEPTIONS = [:comment_id, :user_id]

  before_filter :init_obj_for_change_status, :only => [:change_status]

  # GET /admin/complaints
  def index
    @complaints = Complaint.search({ :term => params[:q], 
                                     :comment_id => params[:comment_id],
                                     :user_id => params[:user_id],
                                     :thread_id => params[:thread_id],
                                     :forum_id => params[:forum_id],
                                     :status => params[:status]},
                                    params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def complaints
    @complaints = Complaint.search({:comment_id => params[:id], :status => :all},
                                   params[:page], LIGHTBOX_PER_PAGE)
    respond_to do |format|
      format.js
    end
  end

  # GET /admin/complaints/1
  # GET /admin/complaints/1.js
  def show
    @complaint = Complaint.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  # GET /admin/complaint/1/show_modal
  # GET /admin/complaint/1/show_modal.js
  def show_modal
    @complaint = Complaint.find(params[:id])
    respond_to do |format|
      format.html { head :not_found }
      format.js
    end
  end
  
  # GET /admin/complaints/new
  def new
    @complaint = Complaint.new
  end

  # GET /admin/complaints/1/edit
  def edit
    @complaint = Complaint.find(params[:id])
  end

  # POST /admin/complaints
  def create
    @complaint = Complaint.new(params[:complaint].except(*MASS_ATTR_EXCEPTIONS))
    @complaint.comment = get_comment params[:complaint][:comment_id]
    @complaint.user = get_user params[:complaint][:user_id]
    if @complaint.save
      redirect_to [:admin, @complaint], notice: t(:creation_success, scope: :action_messages, model: 'Reclamação')
    else
      render action: "new"
    end
  end

  # PUT /admin/complaints/1
  def update
    @complaint = Complaint.find(params[:id])
    if @complaint.update_attributes(params[:complaint].except(*MASS_ATTR_EXCEPTIONS))
      redirect_to [:admin, @complaint], notice: t(:update_success, scope: :action_messages, model: 'Reclamação')
    else
      render action: "edit"
    end
  end

  # DELETE /admin/complaints/1
  def destroy
    @complaint = Complaint.find(params[:id])
    @complaint.destroy
    redirect_to admin_complaints_url, notice: t(:deletion_success, scope: :action_messages, model: 'Reclamação')
  end
  
  private
    
    def init_obj_for_change_status
      @obj = Complaint.find(params[:id])
    end
end

app/views/admin/complaints/_comment_complaint.html.erb
<li class="item" id="complaint_<%= complaint.id %>">
  <div class="item-body">
    <h4 class="item-heading">
      <%= link_to complaint.thread.name, admin_forum_thread_path(complaint.thread) %>
    </h4>
    <spam class="item-heading">
      Usuário: <%= link_to complaint.user.name, admin_user_path(complaint.user) %>
    </spam>
    <span class="item-heading username">
      <b><%= complaint.user.username %></b>
    </span>
    <span class="item-heading time">
      <b><%= time_ago_in_words(complaint.created_at) %></b>
    </span>
    <div class="item-text">
      <%= simple_format complaint.body %>
    </div>
  </div>
  <div class="item-body-footer">
    <spam class="item-footer item-footer-id">
      <strong>ID: <%= complaint.id %></strong>
    </spam>
    <spam class="item-footer item-footer-id">
      <strong>Status: <%= t complaint.status, :scope => :status %></strong>
    </spam>
    <%= link_to "Visualizar", admin_complaint_path(complaint), :class => "item-footer-btn btn-view" %>
    <% generate_status_change_actions(complaint, :complaint).each do |action| %>
        <strong><%= link_to action[:label], action[:path], :remote => true,
                    :data => {:confirm => action[:confirmation_msg], :method => action[:method], :dismiss => "modal"},
                    :class => "item-footer-btn btn-#{action[:type]}" %></strong>
      <% end %>
  </div>
</li>

app/views/admin/complaints/_comment_complaints.html.erb
<%= render :partial => 'comment_complaint', :collection => @complaints, :as => :complaint %>
<% if @complaints.total_pages > @complaints.current_page %>
  <li>
    <b><%= link_to "Ver Mais", complaints_admin_comment_path(params[:id], item_list_class(params[:id]), 
                                                          :page => @complaints.current_page + 1),
                               :class => "btn-read-more", :remote => true,
                               :onclick => "javascript:$(this).parent().parent().remove();" %></b>
  </li>
<% end %>

app/views/admin/complaints/_complaint.html.erb
<% entity_id = "complaint_#{complaint.id}" %>
<li class="item" id="<%= entity_id %>">
  <div class="item-body">
    <span class="item-heading time">
      <b><%= time_ago_in_words(complaint.created_at) %></b>
    </span>
    <div class="item-title">
      <h4 class="item-heading">
        <%= link_to complaint.comment.thread.name, show_modal_admin_forum_thread_path(complaint.comment.thread),
            :remote => true, data: { toggle: "modal", target: "#admin-modal" } %>
      </h4>
    </div>
    <spam class="item-heading">
      Usuário: <%= link_to complaint.user.name, show_modal_admin_user_path(complaint.user),
                   :remote => true, data: { toggle: "modal", target: "#admin-modal" } %>
    </spam>
    <span class="item-heading username">
      <b><%= complaint.user.username %></b>
    </span>
    <div class="item-text">
      <%= simple_format complaint.body %>
    </div>
  </div>
  <div class="item-body-footer">
    <spam class="item-footer item-footer-id">
      <strong>ID: <%= complaint.id %></strong>
    </spam>
    <%= link_to "Visualizar", admin_complaint_path(complaint), :class => "item-footer-btn btn-view" %>
    <%= link_to "Pré-visualizar", show_modal_admin_complaint_path(complaint), :remote => true, 
         :class => "item-footer-btn btn-preview", data: { toggle: "modal", target: "#admin-modal" } %>
    <%= link_to "Comentário", show_modal_admin_comment_path(complaint.comment),
         :remote => true, :class => "item-footer-btn btn-parent",
         data: { toggle: "modal", target: "#admin-modal" } %>
    <spam class="item-footer-right">
      <% generate_status_change_actions(complaint, :complaint).each do |action| %>
        <strong><%= link_to action[:label], action[:path], :remote => true,
                    :data => {:confirm => action[:confirmation_msg], :method => action[:method],
                              :custom_reload => true, :reload_entityid => entity_id },
                    :class => "item-footer-btn btn-#{action[:type]}" %></strong>
      <% end %>
    </spam>
  </div>
</li>

app/views/admin/complaints/_fields.html.erb
<% @complaint.user = User.find_by_id(params[:user_id]) unless params[:user_id].nil? %>
<% user_path = admin_user_path(@complaint.user) unless @complaint.user.nil? %>
<%= render 'shared/admin/select2_js_template',
     :field_name => "complaint_user_id",
     :label => "Usuário",
     :obj => @complaint.user,
     :index_path => admin_users_path,
     :show_path => user_path %>

<%= render 'shared/error_messages', :object => f.object %>
<% unless f.object.new_record? %>
  <%= render 'shared/field_show', :label => "Id", :value => f.object.id %>
  <%= render 'shared/field_show', :label => "Status", :value => t(f.object.status, :scope => :status_label)  %>
<% end %>

<%= render 'shared/field', :f => f, :field_name => :comment_id %>
<%= render 'shared/field', :f => f, :field_name => :user_id %>
<%= render 'shared/field', :f => f, :field_type => :text_area, :field_name => :body %>

app/views/admin/complaints/_show.html.erb
<% javascript 'admin/show' %>

<%= render 'shared/admin_title_options', :title => "Visualização de Reclamação",
           :options => generate_status_change_actions(@complaint, :complaint) +
                       [ {:label => "Voltar", :path => admin_complaints_path, :type => "info"} ] %>

<%= render 'shared/status_message' %>

<%= render 'show_fields' %>

<%= hidden_field_tag 'model_path', admin_complaint_path(@complaint) %>

app/views/admin/complaints/_show_fields.html.erb
<% opened_from_modal ||= false %>

<div class="form-horizontal">
  <%= render 'shared/field_show', :label => "Id", :value => @complaint.id %>
  <%= render 'shared/field_show', :label => "Status", :value => t(@complaint.status, :scope => :status_label) %>
  <%= render 'shared/field_show', :label => "Id do Comentário",
                                  :link => link_to("#{@complaint.comment.id} - #{@complaint.comment.body}", 
                                                    show_modal_admin_comment_path(@complaint.comment),
                                                    :remote => true, data: modal_data_map(opened_from_modal)) %>
  <%= render 'shared/field_show', :label => "Usuário",
                                  :link => link_to("#{@complaint.user.name} (Id: #{@complaint.user.id})", 
                                                    show_modal_admin_user_path(@complaint.user),
                                                    :remote => true, data: modal_data_map(opened_from_modal)) %>
  <%= render 'shared/field_show', :label => "Texto", :value => @complaint.body %>
  <%= render 'shared/field_show', :label => "Criado em", :value => l(@complaint.created_at) %>
  <%= render 'shared/field_show', :label => "Atualizado em", :value => l(@complaint.updated_at) %>
</div>

app/views/admin/complaints/complaints.js.erb
<% if params[:div_class].nil? %>
  <% complaints = "<ul class=\"item-list #{item_list_class(params[:id])}\">#{render :partial => 'comment_complaints'}</ul>" %>
  $(".modal-body-content").html("<%= raw escape_javascript complaints %>");
  $(".modal-title").html("Pré-visualização de Reclamações");
<% else %>
  $(".<%= params[:div_class] %>").append("<%= escape_javascript render :partial => 'comment_complaints' %>");
<% end %>
$(".modal-footer > .extra-buttons").empty();

app/views/admin/complaints/edit.html.erb
<%= render 'shared/admin_title_options', :title => "Atualização de Reclamação",
           :options => [ {:label => "Voltar", :path => admin_complaints_path, :type => "info"} ] %>

<%= form_for([:admin, @complaint], :html => {:class => "form-horizontal"}) do |f| %>
  <%= render 'fields', :f => f %>	
  <div class="controls"> 
    <%= f.submit "Salvar", :class => "btn btn-primary btn-large" %>
  </div>
<% end %>

app/views/admin/complaints/index.html.erb
<% javascript 'admin/list' %>
<% javascript 'admin/custom_reload' %>

<%= render 'shared/admin_title_options', :title => "Lista de Reclamações" %>
<%= render 'shared/status_message' %>

<% forum = Forum.find_by_id(params[:forum_id]) %>
<% forum_path = admin_forum_path(forum) unless forum.blank? %>
<%= render 'shared/admin/select2_js_template',
     :field_name => "forum_id",
     :label => "Forum",
     :obj => forum,
     :index_path => admin_forums_path,
     :show_path => forum_path %>

<% thread = ForumThread.find_by_id(params[:thread_id]) %>
<% thread_path = admin_forum_thread_path(thread) unless thread.blank? %>
<%= render 'shared/admin/select2_js_template',
     :field_name => "thread_id",
     :label => "Thread",
     :obj => thread,
     :index_path => admin_forum_threads_path,
     :show_path => thread_path %>


<% user = User.find_by_id(params[:user_id]) %>
<% user_path = admin_user_path(user) unless user.blank? %>
<%= render 'shared/admin/select2_js_template',
     :field_name => "user_id",
     :label => "Usuário",
     :obj => user,
     :index_path => admin_users_path,
     :show_path => user_path %>

<%= render 'shared/admin/search_form', :path => admin_complaints_path,
      :fields => {:q => {:tag => :text_field_tag, :class => "input-medium search-query"},
                  :status => {:tag => :hidden_field_tag},
                  :forum_id => {:tag => :hidden_field_tag},
                  :thread_id => {:tag => :hidden_field_tag},
                  :user_id => {:tag => :hidden_field_tag}} %>

<%= render 'shared/admin/status_options', :status_options => Complaint.valid_status,
           :status_default => Complaint.default_status_for_search %>

<%= will_paginate %>

<div>
  <ul class="item-list">
  <% if @complaints.length > 0 %>
    <%= render @complaints %>
  <% else %>
    <li class="item-empty"><%= t :complaint, :scope => :empty_list %></li>
  <% end %>
  </ul>
</div>

<%= will_paginate %>

app/views/admin/complaints/index.js.erb
$(".item-list").html("<%= escape_javascript render(@complaints) %>");

app/views/admin/complaints/new.html.erb
<%= render 'shared/admin_title_options', :title => "Nova Comentário",
           :options => [ {:label => "Voltar", :path => admin_complaints_path, :type => "info"} ] %>

<%= form_for([:admin, @complaint], :html => {:class => "form-horizontal"}) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="controls"> 
    <%= f.submit "Salvar", :class => "btn btn-primary btn-large" %>
  </div>
<% end %>

app/views/admin/complaints/show.html.erb
<%= render 'show' %>

app/views/admin/complaints/show.js.erb
$("#content").html("<%= escape_javascript render('show') %>");

app/views/admin/complaints/show_modal.js.erb
$(".modal-body-content").html("<%= escape_javascript render('show_fields', :opened_from_modal => true) %>");
$(".modal-title").html("Pré-visualização de Reclamações");
<%= render "shared/admin/modal_buttons", :obj => @complaint, :resource_name => :complaint %>